module.exports = {
	Headers: {
		CONTROL: "CONTROL",
		FILE: "FILE",
		GPI: "GPI",
		PING: "PING",
		QUIT: "QUIT",
	},

	Controls: {
		LY_FADE_MIX: "LY Fade Mix",
		BACKING_CLR: "Backing Color",
		MONITOR_OUT: "Monitor Out",
		VIDEO_FORMAT: "Video Format",
		TALENT_MIR: "Talent Mirror",
		DUAL_CUR: "Dual Cursor",
		WALL_CUR_ENABLE: "Wall Cursor Position Enable",
		FLOOR_CUR_ENABLE: "Floor Cursor Position Enable",
		CUR_X: "Cursor X",
		CUR_Y: "Cursor Y",
		CUR_2_X: "Cursor 2 X",
		CUR_2_Y: "Cursor 2 Y",
		MATTE_DEN: "Matte Density",
		BLACK_GLOSS: "Black Gloss",
		SHADOW_LEV: "Shadow Level",
		SHADOW_THR: "Shadow Threshold",
		VEIL_MAS: "Veil Master",
		CLEAN_LEV: "Cleanup Level", 
		MATTE_ENABLE: "Matte Enable",
		QUICKLOAD: "Quickload",
		QUICKSAVE: "Quicksave",
		GM_ENABLE: "GM Enable",
		SAMP_WALL: "Sample Wall",
		SAMP_FLOOR: "Sample Floor",
		AUTO_SCN_SAMP: "Auto Screen Sample",
	},

	controls_rotary: [
		{ id: 'matte_density', label: 'Matte Density', min: 0, max: 10000, minPercent: -100, maxPercent: 300 },
		{ id: 'black_gloss', label: 'Black Gloss', min: 0, max: 10000, minPercent: 0, maxPercent: 100 },
		{ id: 'blue_density', label: 'Blue Density', min: 0, max: 10000, minPercent: 0, maxPercent: 100 },
		{ id: 'green_density', label: 'Green Density', min: 0, max: 10000, minPercent: 0, maxPercent: 100 },
		{ id: 'red_density', label: 'Red Density', min: 0, max: 10000, minPercent: 0, maxPercent: 100 },
		{ id: 'shadow_level', label: 'Shadow Level', min: 0, max: 10000, minPercent: 100, maxPercent: 200 },
		{ id: 'shadow_threshold', label: 'Shadow Threshold', min: 0, max: 10000, minPercent: 0, maxPercent: 100 },
		{ id: 'matte_correct_horizontal_size', label: 'Matte Correct Horizontal Size', min: 0, max: 6 },
		{ id: 'matte_correct_vertical_size', label: 'Matte Correct Vertical Size', min: 0, max: 3 },
		{ id: 'cursor_x', label: 'Cursor X', min: 0, max: 10000 },
		{ id: 'cursor_y', label: 'Cursor Y', min: 0, max: 10000 },
		{ id: 'cursor_2_x', label: 'Cursor 2 X', min: 0, max: 10000 },
		{ id: 'cursor_2_y', label: 'Cursor 2 Y', min: 0, max: 10000 },
		{ id: 'veil_master', label: 'Veil Master', min: 0, max: 10000 },
		{ id: 'veil_red', label: 'Veil Red', min: 0, max: 10000 },
		{ id: 'veil_green', label: 'Veil Green', min: 0, max: 10000 },
		{ id: 'veil_blue', label: 'Veil Blue', min: 0, max: 10000 },
		{ id: 'veil_correct_horizontal_size', label: 'Veil Correct Horizontal Size', min: 0, max: 6 },
		{ id: 'veil_correct_vertical_size', label: 'Veil Correct Vertical Size', min: 0, max: 61 },
		{ id: 'wall_color_red', label: 'Wall Color Red', min: 0, max: 10000 },
		{ id: 'wall_color_green', label: 'Wall Color Green', min: 0, max: 10000 },
		{ id: 'wall_color_blue', label: 'Wall Color Blue', min: 0, max: 10000 },
		{ id: 'floor_color_red', label: 'Floor Color Red', min: 0, max: 10000 },
		{ id: 'floor_color_green', label: 'Floor Color Green', min: 0, max: 10000 },
		{ id: 'floor_color_blue', label: 'Floor Color Blue', min: 0, max: 10000 },
		{ id: 'cleanup_level', label: 'Clean Up Level', min: 0, max: 10000, minPercent: 0, maxPercent: 100 },
		{ id: 'cleanup_dark_recover', label: 'Cleanup Dark Recover', min: 0, max: 10000 },
		{ id: 'cleanup_light_recover', label: 'Cleanup Light Recover', min: 0, max: 10000 },
		{ id: 'cleanup_strength', label: 'Cleanup Strength', min: 0, max: 10000 },
		{ id: 'gm_cleanup_level', label: 'GM Cleanup Level', min: 0, max: 10000 },
		{ id: 'gm_cleanup_dark_recover', label: 'GM Cleanup Dark Recover', min: 0, max: 10000 },
		{ id: 'gm_cleanup_light_recover', label: 'GM Cleanup Light Recover', min: 0, max: 10000 },
		{ id: 'gm_cleanup_strength', label: 'GM Cleanup Strength', min: 0, max: 10000 },
		{ id: 'correction_level', label: 'Correction Level', min: 0, max: 10000 },
		{ id: 'noise_level', label: 'Noise Level', min: 0, max: 10000 },
		{ id: 'black_balance', label: 'Black Balance', min: 0, max: 10000 },
		{ id: 'gray_balance', label: 'Gray Balance', min: 0, max: 10000 },
		{ id: 'white_balance', label: 'White Balance', min: 0, max: 10000 },
		{ id: 'flare_level', label: 'Flare Level', min: 0, max: 10000 },
		{ id: 'cool', label: 'Cool', min: 0, max: 10000 },
		{ id: 'skin_tone', label: 'Skin Tone', min: 0, max: 10000 },
		{ id: 'light_warm', label: 'Light Warm', min: 0, max: 10000 },
		{ id: 'dark_warm', label: 'Dark Warm', min: 0, max: 10000 },
		{ id: 'flare_correct_horizontal_size', label: 'Flare Correct Horizontal Size', min: 0, max: 6 },
		{ id: 'flare_correct_vertical_size', label: 'Flare Correct Vertical Size', min: 0, max: 61 },
		{ id: 'ambiance_master', label: 'Ambiance Master', min: 0, max: 10000 },
		{ id: 'ambiance_red', label: 'Ambiance Red', min: 0, max: 10000 },
		{ id: 'ambiance_green', label: 'Ambiance Green', min: 0, max: 10000 },
		{ id: 'ambiance_blue', label: 'Ambiance Blue', min: 0, max: 10000 },
		{ id: 'ambiance_strength', label: 'Ambiance Strength', min: 0, max: 10000 },
		{ id: 'direct_light_red', label: 'Direct Light Red', min: 0, max: 10000 },
		{ id: 'direct_light_green', label: 'Direct Light Green', min: 0, max: 10000 },
		{ id: 'direct_light_blue', label: 'Direct Light Blue', min: 0, max: 10000 },
		{ id: 'direct_light_mix', label: 'Direct Light Mix', min: 0, max: 10000 },
		{ id: 'vertical_blur', label: 'Vertical Blur', min: 0, max: 10000 },
		{ id: 'fg_saturation_red', label: 'FG Saturation Red', min: 0, max: 10000 },
		{ id: 'fg_saturation_green', label: 'FG Saturation Green', min: 0, max: 10000 },
		{ id: 'fg_saturation_blue', label: 'FG Saturation Blue', min: 0, max: 10000 },
		{ id: 'fg_saturation_master', label: 'FG Saturation Master', min: 0, max: 10000 },
		{ id: 'fg_contrast_red', label: 'FG Contrast Red', min: 0, max: 10000 },
		{ id: 'fg_contrast_green', label: 'FG Contrast Green', min: 0, max: 10000 },
		{ id: 'fg_contrast_blue', label: 'FG Contrast Blue', min: 0, max: 10000 },
		{ id: 'fg_contrast_master', label: 'FG Contrast Master', min: 0, max: 10000 },
		{ id: 'fg_black_red', label: 'FG Black Red', min: 0, max: 10000 },
		{ id: 'fg_black_green', label: 'FG Black Green', min: 0, max: 10000 },
		{ id: 'fg_black_blue', label: 'FG Black Blue', min: 0, max: 10000 },
		{ id: 'fg_black_master', label: 'FG Black Master', min: 0, max: 10000 },
		{ id: 'fg_white_red', label: 'FG White Red', min: 0, max: 10000 },
		{ id: 'fg_white_green', label: 'FG White Green', min: 0, max: 10000 },
		{ id: 'fg_white_blue', label: 'FG White Blue', min: 0, max: 10000 },
		{ id: 'fg_white_master', label: 'FG White Master', min: 0, max: 10000 },
		{ id: 'fg_contrast_crossover', label: 'FG Contrast Crossover', min: 0, max: 10000 },
		{ id: 'fade_mix', label: 'Fade Mix', min: 0, max: 10000 },
		{ id: 'bg_saturation_red', label: 'BG Saturation Red', min: 0, max: 10000 },
		{ id: 'bg_saturation_green', label: 'BG Saturation Green', min: 0, max: 10000 },
		{ id: 'bg_saturation_blue', label: 'BG Saturation Blue', min: 0, max: 10000 },
		{ id: 'bg_saturation_master', label: 'BG Saturation Master', min: 0, max: 10000 },
		{ id: 'bg_contrast_red', label: 'BG Contrast Red', min: 0, max: 10000 },
		{ id: 'bg_contrast_green', label: 'BG Contrast Green', min: 0, max: 10000 },
		{ id: 'bg_contrast_blue', label: 'BG Contrast Blue', min: 0, max: 10000 },
		{ id: 'bg_contrast_master', label: 'BG Contrast Master', min: 0, max: 10000 },
		{ id: 'bg_black_red', label: 'BG Black Red', min: 0, max: 10000 },
		{ id: 'bg_black_green', label: 'BG Black Green', min: 0, max: 10000 },
		{ id: 'bg_black_blue', label: 'BG Black Blue', min: 0, max: 10000 },
		{ id: 'bg_black_master', label: 'BG Black Master', min: 0, max: 10000 },
		{ id: 'bg_white_red', label: 'BG White Red', min: 0, max: 10000 },
		{ id: 'bg_white_green', label: 'BG White Green', min: 0, max: 10000 },
		{ id: 'bg_white_blue', label: 'BG White Blue', min: 0, max: 10000 },
		{ id: 'bg_white_master', label: 'BG White Master', min: 0, max: 10000 },
		{ id: 'bg_contrast_crossover', label: 'BG Contrast Crossover', min: 0, max: 10000 },
		{ id: 'bg_filter', label: 'BG Filter', min: 0, max: 10000 },
		{ id: 'test_signal_master', label: 'Test Signal Master', min: 0, max: 10000 },
		{ id: 'test_signal_red', label: 'Test Signal Red', min: 0, max: 10000 },
		{ id: 'test_signal_green', label: 'Test Signal Green', min: 0, max: 10000 },
		{ id: 'test_signal_blue', label: 'Test Signal Blue', min: 0, max: 10000 },
		{ id: 'ly_saturation_red', label: 'LY Saturation Red', min: 0, max: 10000 },
		{ id: 'ly_saturation_green', label: 'LY Saturation Green', min: 0, max: 10000 },
		{ id: 'ly_saturation_blue', label: 'LY Saturation Blue', min: 0, max: 10000 },
		{ id: 'ly_saturation_master', label: 'LY Saturation Master', min: 0, max: 10000 },
		{ id: 'ly_contrast_red', label: 'LY Contrast Red', min: 0, max: 10000 },
		{ id: 'ly_contrast_green', label: 'LY Contrast Green', min: 0, max: 10000 },
		{ id: 'ly_contrast_blue', label: 'LY Contrast Blue', min: 0, max: 10000 },
		{ id: 'ly_contrast_master', label: 'LY Contrast Master', min: 0, max: 10000 },
		{ id: 'ly_black_red', label: 'LY Black Red', min: 0, max: 10000 },
		{ id: 'ly_black_green', label: 'LY Black Green', min: 0, max: 10000 },
		{ id: 'ly_black_blue', label: 'LY Black Blue', min: 0, max: 10000 },
		{ id: 'ly_black_master', label: 'LY Black Master', min: 0, max: 10000 },
		{ id: 'ly_white_red', label: 'LY White Red', min: 0, max: 10000 },
		{ id: 'ly_white_green', label: 'LY White Green', min: 0, max: 10000 },
		{ id: 'ly_white_blue', label: 'LY White Blue', min: 0, max: 10000 },
		{ id: 'ly_white_master', label: 'LY White Master', min: 0, max: 10000 },
		{ id: 'ly_contrast_crossover', label: 'LY Contrast Crossover', min: 0, max: 10000 },
		{ id: 'ly_filter', label: 'LY Filter', min: 0, max: 10000 },
		{ id: 'ly_test_signal_master', label: 'LY Test Signal Master', min: 0, max: 10000 },
		{ id: 'ly_test_signal_red', label: 'LY Test Signal Red', min: 0, max: 10000 },
		{ id: 'ly_test_signal_green', label: 'LY Test Signal Green', min: 0, max: 10000 },
		{ id: 'ly_test_signal_blue', label: 'LY Test Signal Blue', min: 0, max: 10000 },
		{ id: 'ly_fade_mix', label: 'LY Fade Mix', min: 0, max: 10000 },
		{ id: 'lighting_level_red', label: 'Lighting Level Red', min: 0, max: 10000 },
		{ id: 'lighting_level_green', label: 'Lighting Level Green', min: 0, max: 10000 },
		{ id: 'lighting_level_blue', label: 'Lighting Level Blue', min: 0, max: 10000 },
		{ id: 'lighting_level_master', label: 'Lighting Level Master', min: 0, max: 10000 },
		{ id: 'lighting_minimum_level', label: 'Lighting Minimum Level', min: 0, max: 10000 },
		{ id: 'window_position_top', label: 'Window Position Top', min: 0, max: 10000 },
		{ id: 'window_position_bottom', label: 'Window Position Bottom', min: 0, max: 10000 },
		{ id: 'window_position_left', label: 'Window Position Left', min: 0, max: 10000 },
		{ id: 'window_position_right', label: 'Window Position Right', min: 0, max: 10000 },
		{ id: 'window_softness_top', label: 'Window Softness Top', min: 0, max: 10000 },
		{ id: 'window_softness_bottom', label: 'Window Softness Bottom', min: 0, max: 10000 },
		{ id: 'window_softness_left', label: 'Window Softness Left', min: 0, max: 10000 },
		{ id: 'window_softness_right', label: 'Window Softness Right', min: 0, max: 10000 },
		{ id: 'window_skew_top', label: 'Window Skew Top', min: 0, max: 10000 },
		{ id: 'window_skew_bottom', label: 'Window Skew Bottom', min: 0, max: 10000 },
		{ id: 'window_skew_left', label: 'Window Skew Left', min: 0, max: 10000 },
		{ id: 'window_skew_right', label: 'Window Skew Right', min: 0, max: 10000 },
		{ id: 'window_skew_offset_top', label: 'Window Skew Offset Top', min: 0, max: 10000 },
		{ id: 'window_skew_offset_bottom', label: 'Window Skew Offset Bottom', min: 0, max: 10000 },
		{ id: 'window_skew_offset_left', label: 'Window Skew Offset Left', min: 0, max: 10000 },
		{ id: 'window_skew_offset_right', label: 'Window Skew Offset Right', min: 0, max: 10000 },
		{ id: 'transition_rate', label: 'Transition Rate', min: 1, max: 120 },
		{ id: 'bm_process_horizontal', label: 'BM Process Horizontal', min: 0, max: 3 },
		{ id: 'bm_process_vertical', label: 'BM Process Vertical', min: 0, max: 3 },
		{ id: 'bm_filter', label: 'BM Filter', min: 0, max: 10000 },
		{ id: 'bm_input_level', label: 'BM Input Level', min: 0, max: 10000 },
		{ id: 'bm_input_offset', label: 'BM Input Offset', min: 0, max: 10000 },
		{ id: 'gm_process_horizontal', label: 'GM Process Horizontal', min: 0, max: 3 },
		{ id: 'gm_process_vertical', label: 'GM Process Vertical', min: 0, max: 3 },
		{ id: 'gm_filter', label: 'GM Filter', min: 0, max: 10000 },
		{ id: 'gm_input_level', label: 'GM Input Level', min: 0, max: 10000 },
		{ id: 'gm_input_offset', label: 'GM Input Offset', min: 0, max: 10000 },
		{ id: 'hm_process_horizontal', label: 'HM Process Horizontal', min: 0, max: 3 },
		{ id: 'hm_process_vertical', label: 'HM Process Vertical', min: 0, max: 3 },
		{ id: 'hm_filter', label: 'HM Filter', min: 0, max: 10000 },
		{ id: 'hm_input_level', label: 'HM Input Level', min: 0, max: 10000 },
		{ id: 'hm_input_offset', label: 'HM Input Offset', min: 0, max: 10000 },
		{ id: 'lm_process_horizontal', label: 'LM Process Horizontal', min: 0, max: 3 },
		{ id: 'lm_process_vertical', label: 'LM Process Vertical', min: 0, max: 3 },
		{ id: 'lm_filter', label: 'LM Filter', min: 0, max: 10000 },
		{ id: 'lm_input_level', label: 'LM Input Level', min: 0, max: 10000 },
		{ id: 'lm_input_offset', label: 'LM Input Offset', min: 0, max: 10000 },
		{ id: 'noise_cursor_x', label: 'Noise Cursor X', min: 0, max: 10000 },
		{ id: 'noise_cursor_y', label: 'Noise Cursor Y', min: 0, max: 10000 },
		{ id: 'fg_input_frame_delay', label: 'FG Input Frame Delay', min: 0, max: 14 },
		{ id: 'fg_input_u_position', label: 'FG Input U Position', min: 0, max: 10000 },
		{ id: 'fg_input_v_position', label: 'FG Input V Position', min: 0, max: 10000 },
		{ id: 'fg_input_uv_position', label: 'FG Input UV Position', min: 0, max: 10000 },
		{ id: 'talent_highlight_level', label: 'Talent Highlight Level', min: 0, max: 10000 },
		{ id: 'monitor_highlight_level', label: 'Monitor Highlight Level', min: 0, max: 10000 },
		{ id: 'matte_out_level', label: 'Matte Out Level', min: 0, max: 10000 },
		{ id: 'output_offset', label: 'Output Offset', min: -1500, max: 1500 },
		{ id: 'gp_out_delay', label: 'GP Out Delay', min: 1, max: 120 },
		{ id: 'gp_1_input_delay', label: 'GP 1 Input Delay', min: 1, max: 120 },
		{ id: 'gp_2_input_delay', label: 'GP 2 Input Delay', min: 1, max: 120 },
		{ id: 'gp_3_input_delay', label: 'GP 3 Input Delay', min: 1, max: 120 },
		{ id: 'gp_4_input_delay', label: 'GP 4 Input Delay', min: 1, max: 120 },
		{ id: 'gp_5_input_delay', label: 'GP 5 Input Delay', min: 1, max: 120 },
	]
}